changelog:
  exclude:
    labels:
      - ignore*
      - github*
    authors:
      - octocat
  categories:
    - title: 🛠️ Breaking Changes
      labels:
        - breaking-change
    - title: 🎯 Features
      labels:
        - feature
        - enhancement
    - title: 🩹 Fixes
      labels:
        - bug
        - fix
    - title: 🧹 Others
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: 👒 Dependencies
      labels:
        - dependencies