title: Yurg's Dev Map
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
search_enabled: false
mermaid_enabled: false
auto_page_title: false
sidebar:
  - welcome
  - contributors
  - recommendations
  - known-issues
  - support
  - download
